from typing import Protocol, Any, Tuple, List, Optional


class DBConnection(Protocol):
    def execute(self, query: str, params: Tuple[Any, ...] = ()) -> None: ...
    def fetchone(self, query: str, params: Tuple[Any, ...] = ()) -> Optional[Tuple[Any, ...]]: ...
    def fetchall(self, query: str, params: Tuple[Any, ...] = ()) -> List[Tuple[Any, ...]]: ...