from typing import Protocol, TypeVar, Optional
from uuid import UUID


T = TypeVar("T")


class Repository(Protocol[T]):
    def get_by_id(self, id: UUID) -> Optional[T]: ...
    def insert(self, entity: T) -> None: ...
    def update(self, entity: T) -> None: ...
    def delete(self, id: UUID) -> None: ...
